# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt
  - pip install -U tox-travis dredd_hooks
  - sudo apt-get install -y nodejs npm # for dredd
  - npm install -g dredd

# Command to run tests, e.g. python setup.py test
script: tox
