swagger: '2.0'
info:
  title: Variants and Calls API demo
  version: "1"
basePath: /v1
consumes:
  - application/json
produces:
  - application/json

paths:
  /individuals:
    post:
      operationId: python_model_service.api.operations.post_individual
      summary: Add an individual to the database
      parameters:
        - name: individual
          in: body
          schema:
            $ref: '#/definitions/Individual'
            example:
              description: "Subject 17"
      responses:
        201:
          description: New individual created
          schema:
            $ref: "#/definitions/Individual"
          headers:
            Location:
              type: string
              format: url
        400:
          description: Variant provided in body does not pass schema validation
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Forbidden to overwrite variant in post
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error - Variant not created
          schema:
            $ref: "#/definitions/Error"
    get:
      operationId: python_model_service.api.operations.get_individuals
      summary: Get all individuals
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            example: []
            items:
              $ref: '#/definitions/Individual'
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /individuals/{individual_id}:
    get:
      operationId: python_model_service.api.operations.get_one_individual
      summary: Get specific individual
      parameters:
        - $ref: '#/parameters/individual_id'
      responses:
        200:
          description: Return individual
          schema:
            $ref: '#/definitions/Individual'
        404:
          description: Individual not found
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /variants:
    post:
      operationId: python_model_service.api.operations.post_variant
      summary: Add a variant to the database
      parameters:
        - name: variant
          in: body
          schema:
            $ref: '#/definitions/Variant'
            example:
              name: "rs6054257"
              chromosome: "chr1"
              start: 14370
              ref: "G"
              alt: "A"
      responses:
        201:
          description: New variant created
        405:
          description: Cannot overwrite variant
    get:
      operationId: python_model_service.api.operations.get_variants
      summary: Get all variants within genomic range
      parameters:
        - name: chromosome
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
          x-example: "chr1"
          required: true
        - name: start
          in: query
          type: integer
          minimum: 1
          x-example: 1
          required: true
        - name: end
          in: query
          type: integer
          minimum: 1
          x-example: 100000
          required: true
      responses:
        200:
          description: Return variants
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
            example: []

  /variants/{variant_id}:
    get:
      operationId: python_model_service.api.operations.get_one_variant
      summary: Get specific variant
      parameters:
        - $ref: '#/parameters/variant_id'
      responses:
        200:
          description: Return variant
          schema:
            $ref: '#/definitions/Variant'
        404:
          description: Variant not found
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /calls:
    post:
      operationId: python_model_service.api.operations.post_call
      summary: Add a call to the database
      parameters:
        - name: call
          in: body
          schema:
            $ref: '#/definitions/Call'
            example:
              individual_id: bf3ba75b-8dfe-4619-b832-31c4a087a589
              variant_id: bf3ba75b-8dfe-4619-b832-31c4a087a589
              genotype: "0/1"
              fmt: "GQ:DP:HQ 48:1:51,51"
      responses:
        201:
          description: New call created
        405:
          description: Cannot overwrite call
    get:
      operationId: python_model_service.api.operations.get_calls
      summary: Get all calls
      responses:
        200:
          description: Return calls
          schema:
            type: array
            items:
              $ref: '#/definitions/Call'
            example: []

  /calls/{call_id}:
    get:
      operationId: python_model_service.api.operations.get_one_call
      summary: Get specific call
      parameters:
        - $ref: '#/parameters/call_id'
      responses:
        200:
          description: Return call
          schema:
            $ref: '#/definitions/Call'
        404:
          description: Call not found
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /individuals/{individual_id}/variants:
    get:
      operationId: python_model_service.api.operations.get_variants_by_individual
      summary: Get variants called in an individual
      parameters:
        - $ref: '#/parameters/individual_id'
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
        404:
          description: Individual does not exist
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'

  /variants/{variant_id}/individuals:
    get:
      operationId: python_model_service.api.operations.get_individuals_by_variant
      summary: Get individuals with a given variant called
      parameters:
        - $ref: '#/parameters/variant_id'
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Individual'
            example: []
        404:
          description: Variant does not exist
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'


parameters:
  variant_id:
    name: variant_id
    description: Variant unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true

  individual_id:
    name: individual_id
    description: Individual unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true

  call_id:
    name: call_id
    description: Call unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true


definitions:
  Individual:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        format: uuid
        description: Unique identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      description:
        type: string
        description: description of individual
        example: "Subject 17"
        minLength: 1
        maxLength: 100
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true

  Call:
    type: object
    required:
      - individual_id
      - variant_id
      - genotype
    properties:
      id:
        description: Unique identifier
        type: string
        format: uuid
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      individual_id:
        type: string
        format: uuid
        description: Unique identifier of individual
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
      variant_id:
        description: Unique identifier of variant
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
      genotype:
        type: string
        description: Called genotype
        example: "0/1"
      fmt:
        type: string
        description: Additional call information
        example: "GQ:DP:HQ 48:1:51,51"
        minLength: 0
        maxLength: 100
        default: ""
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true

  Variant:
    type: object
    required:
      - chromosome
      - start
      - ref
      - alt
    properties:
      id:
        description: Unique identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      name:
        type: string
        description: variant name if any
        example: "rs6054257"
        minLength: 0
        maxLength: 100
        default: ""
      chromosome:
        type: string
        description: Chromosome variant occurs on
        example: "chr1"
        minLength: 1
        maxLength: 10
      start:
        type: integer
        description: Beginning location of variant (1-indexed, like VCF)
        example: 14370
      ref:
        type: string
        description: Reference bases
        example: "G"
      alt:
        type: string
        description: Alternate (variant) vases
        example: "A"

  Error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
